### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by kavezo** [earosenberg/lang-club#3]
Hi! I was wondering how you guys were able to host this on a Stanford website?

**Comment by earosenberg** [comment]
The short version is that everyone with a full-service SUNet ID has their own personal page at stanford.edu/~SUNet so we just hosted on Arthur's page stanford.edu/~atsang2. You do this by putting the files in your WWW folder either with the AFS tool or directly with scp: some more details here https://uit.stanford.edu/service/web/centralhosting/howto_user
Doing it manually would probably look something like 
`scp -r lang-club SUNET@rice.stanford.edu:~/WWW/`
Arthur (@arthur-tsang ) had some short script that made updating it easy.
Alternatively, if you guys have gotten around to making Languages Club an official (registered with ASSU) student group, you should be able to get a dedicated languages club page. Probably contact University IT about this (see eg links from here https://uit.stanford.edu/service/stanfordsites)
Let me know if you have any trouble / more questions, and hopefully Arthur will send the script. Glad to see you're bringing the page back online!

**Comment by kavezo** [comment]
Ooh awesome, thank you so much, I'll look into that!

**Comment by arthur-tsang** [comment]
Hi kavezo,
It's been good to see that the club is doing well! And please feel free to ask us more questions if they arise!
My script was actually very low-tech. It basically just involved adding the lines:
``cd ~/WWW/lang-club``
``git pull``
``cd -``
to my `.bashrc` file (or `.tshrc` or whatever the case may be), and then logging into `myth` or `corn` every time I wanted to update. This became a de facto automatic update last Spring when I was taking Physics 100 and `ssh`ing into `corn` all the time.
Best,
Arthur

**Comment by kavezo** [comment]
Awesome, thanks! I'm also taking CS110 this quarter so that might work out especially well haha

**Comment by earosenberg** [comment]
Looks like this is all figured out, again let us know if you need anything else! And I encourage looking into getting a separate (ie non-user) page / url
